### ISSUE TITLE
Curious about the motivation 

### ISSUE THREAD

**Issue by Fredtoby** [SamusRam/traffic_lights#11]
Hello, Samus, great work! I have some questions about this project:

(1) Since an sdv is always equipped with multiple sensors, it is quite possible that the vehicle can have the information of traffic lights, not only the color of the light but also the remaining time of the current phase. So I'm very curious about your motivation for this work. 

(2) I think what is more important is to predict when will the phase shift. Is it possible to infer it from this dataset? Thank you so much.

**Comment by SamusRam** [comment]
Hi @Fredtoby , sorry for a very late reply! I somehow missed your issue!

(1) Absolutely! The ideal scenario will be to communicate it directly. But before the unified protocols for traffic-light <--> svd protocols are in place, I think svd will have to rely on some predictive models to estimate it. Regarding the motivation, I just saw a cool dataset, played with it, and was curious if it's possible to predict the lights :)

(2) If I understood your question correctly, yes, it is possible! Actually, I even tried modelling Weibull distribution of time before the phase shift (please see here: https://github.com/SamusRam/traffic-lights-modeling/blob/master/lyft_trajectories/model/tl_light_predictor_intersection.py), but it wasn't straightforward
